### ISSUE TITLE
TBXML ARC Issue

### ISSUE THREAD

**Issue by coding-sorcerer** [codebots-ltd/TBXML#15]
I favor using ARC in all of the apps I develop but I'm having a lot of trouble getting TBXML  to function with ARC. Will there be a future release build that is compatible with ARC without having to modify any of the classes? Thanks in advance.

**Comment by OrionSeven** [comment]
What problems are you having? If you #define ARC_ENABLED TBXML will use ARC.

**Comment by MartinMReed** [comment]
Defining that doesn't make it automatically use ARC. You need to set `-fobjc-arc` on the m file. For required updates to the TBXML code see #23.
