### ISSUE TITLE
Block callbacks: Parameter names are not specified

### ISSUE THREAD

**Issue by avrahamshukron** [codebots-ltd/TBXML#4]
In the definition of all the blocks used in TBXML, the parameter names are not specified so there is no way to know what each parameter represents without digging into the TBXML.m file.

Example:
typedef void (^TBXMLIterateAttributeBlock)(TBXMLAttribute *, NSString *, NSString *);

Should be:
typedef void (^TBXMLIterateAttributeBlock)(TBXMLAttribute *attribute, NSString *name, NSString *value);

**Comment by Tpbradley** [comment]
Hi Avrahamshuk,

I've added the parameter names into the latest commit as suggested. Thanks!
